- name: Install Mysql databse
     apt: name={{ item }} state=present
     with_items:
      - mysql-server
      - mysql-client
   - name: Start Mysql service
     service:
      name: mysql
      state: started
      enabled: yes
   - name: Create application databse
     mysql_db: name=employee_db state=present
   - name: Create database user
     mysql_user:
      name: db_user
      password: Passw0rd
      priv: '*.*:ALL'
      state: present
      host: '%'
   - name: install python flask dependency
     pip: 
      name: {{ item }}
      state: present
     with_items:
      - flask
      - flask-mysql
   - name: Copy source code
     copy: src=app.py dest /opt/app.py
   - name: Start web server
     shell: FLASK_APP=app.py nohup flask run --host=0.0.0.0 &